/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportUsRouteImport } from './routes/support-us'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as R365RouteImport } from './routes/365'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreelancersIndexRouteImport } from './routes/freelancers.index'
import { Route as FindClientsIndexRouteImport } from './routes/find-clients.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ResourcesOutreachTemplatesRouteImport } from './routes/resources.outreach-templates'
import { Route as ResourcesGoogleMyBusinessRouteImport } from './routes/resources.google-my-business'
import { Route as ResourcesExportGuideRouteImport } from './routes/resources.export-guide'
import { Route as FreelancersSlugRouteImport } from './routes/freelancers.$slug'
import { Route as FindClientsWebDeveloperRouteImport } from './routes/find-clients.web-developer'
import { Route as FindClientsUnitedStatesRouteImport } from './routes/find-clients.united-states'
import { Route as FindClientsLondonRouteImport } from './routes/find-clients.london'
import { Route as FindClientsLagosRouteImport } from './routes/find-clients.lagos'
import { Route as FindClientsGraphicDesignerRouteImport } from './routes/find-clients.graphic-designer'
import { Route as FindClientsDubaiRouteImport } from './routes/find-clients.dubai'
import { Route as FindClientsCopywriterRouteImport } from './routes/find-clients.copywriter'
import { Route as FindClientsCategoryRouteImport } from './routes/find-clients.$category'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as B2bCategoryRouteImport } from './routes/b2b.$category'
import { Route as AppUpgradeRouteImport } from './routes/app.upgrade'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSafetyRouteImport } from './routes/app.safety'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAiGeneratorRouteImport } from './routes/app.ai-generator'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as FindClientsSkillCityRouteImport } from './routes/find-clients.$skill.$city'
import { Route as AppSettingsSubscriptionRouteImport } from './routes/app.settings.subscription'
import { Route as AppSettingsProfileRouteImport } from './routes/app.settings.profile'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppSettingsDangerZoneRouteImport } from './routes/app.settings.danger-zone'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportUsRoute = SupportUsRouteImport.update({
  id: '/support-us',
  path: '/support-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R365Route = R365RouteImport.update({
  id: '/365',
  path: '/365',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersIndexRoute = FreelancersIndexRouteImport.update({
  id: '/freelancers/',
  path: '/freelancers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClientsIndexRoute = FindClientsIndexRouteImport.update({
  id: '/find-clients/',
  path: '/find-clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ResourcesOutreachTemplatesRoute =
  ResourcesOutreachTemplatesRouteImport.update({
    id: '/resources/outreach-templates',
    path: '/resources/outreach-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesGoogleMyBusinessRoute =
  ResourcesGoogleMyBusinessRouteImport.update({
    id: '/resources/google-my-business',
    path: '/resources/google-my-business',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesExportGuideRoute = ResourcesExportGuideRouteImport.update({
  id: '/resources/export-guide',
  path: '/resources/export-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersSlugRoute = FreelancersSlugRouteImport.update({
  id: '/freelancers/$slug',
  path: '/freelancers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClientsWebDeveloperRoute = FindClientsWebDeveloperRouteImport.update({
  id: '/find-clients/web-developer',
  path: '/find-clients/web-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClientsUnitedStatesRoute = FindClientsUnitedStatesRouteImport.update({
  id: '/find-clients/united-states',
  path: '/find-clients/united-states',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClientsLondonRoute = FindClientsLondonRouteImport.update({
  id: '/find-clients/london',
  path: '/find-clients/london',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClientsLagosRoute = FindClientsLagosRouteImport.update({
  id: '/find-clients/lagos',
  path: '/find-clients/lagos',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClientsGraphicDesignerRoute =
  FindClientsGraphicDesignerRouteImport.update({
    id: '/find-clients/graphic-designer',
    path: '/find-clients/graphic-designer',
    getParentRoute: () => rootRouteImport,
  } as any)
const FindClientsDubaiRoute = FindClientsDubaiRouteImport.update({
  id: '/find-clients/dubai',
  path: '/find-clients/dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClientsCopywriterRoute = FindClientsCopywriterRouteImport.update({
  id: '/find-clients/copywriter',
  path: '/find-clients/copywriter',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClientsCategoryRoute = FindClientsCategoryRouteImport.update({
  id: '/find-clients/$category',
  path: '/find-clients/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bCategoryRoute = B2bCategoryRouteImport.update({
  id: '/b2b/$category',
  path: '/b2b/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiGeneratorRoute = AppAiGeneratorRouteImport.update({
  id: '/ai-generator',
  path: '/ai-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const FindClientsSkillCityRoute = FindClientsSkillCityRouteImport.update({
  id: '/find-clients/$skill/$city',
  path: '/find-clients/$skill/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsSubscriptionRoute = AppSettingsSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsDangerZoneRoute = AppSettingsDangerZoneRouteImport.update({
  id: '/danger-zone',
  path: '/danger-zone',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/365': typeof R365Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/ai-generator': typeof AppAiGeneratorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/templates': typeof AppTemplatesRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/b2b/$category': typeof B2bCategoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/find-clients/$category': typeof FindClientsCategoryRoute
  '/find-clients/copywriter': typeof FindClientsCopywriterRoute
  '/find-clients/dubai': typeof FindClientsDubaiRoute
  '/find-clients/graphic-designer': typeof FindClientsGraphicDesignerRoute
  '/find-clients/lagos': typeof FindClientsLagosRoute
  '/find-clients/london': typeof FindClientsLondonRoute
  '/find-clients/united-states': typeof FindClientsUnitedStatesRoute
  '/find-clients/web-developer': typeof FindClientsWebDeveloperRoute
  '/freelancers/$slug': typeof FreelancersSlugRoute
  '/resources/export-guide': typeof ResourcesExportGuideRoute
  '/resources/google-my-business': typeof ResourcesGoogleMyBusinessRoute
  '/resources/outreach-templates': typeof ResourcesOutreachTemplatesRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/find-clients/': typeof FindClientsIndexRoute
  '/freelancers/': typeof FreelancersIndexRoute
  '/app/settings/danger-zone': typeof AppSettingsDangerZoneRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/subscription': typeof AppSettingsSubscriptionRoute
  '/find-clients/$skill/$city': typeof FindClientsSkillCityRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/365': typeof R365Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/ai-generator': typeof AppAiGeneratorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/b2b/$category': typeof B2bCategoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/find-clients/$category': typeof FindClientsCategoryRoute
  '/find-clients/copywriter': typeof FindClientsCopywriterRoute
  '/find-clients/dubai': typeof FindClientsDubaiRoute
  '/find-clients/graphic-designer': typeof FindClientsGraphicDesignerRoute
  '/find-clients/lagos': typeof FindClientsLagosRoute
  '/find-clients/london': typeof FindClientsLondonRoute
  '/find-clients/united-states': typeof FindClientsUnitedStatesRoute
  '/find-clients/web-developer': typeof FindClientsWebDeveloperRoute
  '/freelancers/$slug': typeof FreelancersSlugRoute
  '/resources/export-guide': typeof ResourcesExportGuideRoute
  '/resources/google-my-business': typeof ResourcesGoogleMyBusinessRoute
  '/resources/outreach-templates': typeof ResourcesOutreachTemplatesRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/find-clients': typeof FindClientsIndexRoute
  '/freelancers': typeof FreelancersIndexRoute
  '/app/settings/danger-zone': typeof AppSettingsDangerZoneRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/subscription': typeof AppSettingsSubscriptionRoute
  '/find-clients/$skill/$city': typeof FindClientsSkillCityRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/365': typeof R365Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/ai-generator': typeof AppAiGeneratorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/templates': typeof AppTemplatesRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/b2b/$category': typeof B2bCategoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/find-clients/$category': typeof FindClientsCategoryRoute
  '/find-clients/copywriter': typeof FindClientsCopywriterRoute
  '/find-clients/dubai': typeof FindClientsDubaiRoute
  '/find-clients/graphic-designer': typeof FindClientsGraphicDesignerRoute
  '/find-clients/lagos': typeof FindClientsLagosRoute
  '/find-clients/london': typeof FindClientsLondonRoute
  '/find-clients/united-states': typeof FindClientsUnitedStatesRoute
  '/find-clients/web-developer': typeof FindClientsWebDeveloperRoute
  '/freelancers/$slug': typeof FreelancersSlugRoute
  '/resources/export-guide': typeof ResourcesExportGuideRoute
  '/resources/google-my-business': typeof ResourcesGoogleMyBusinessRoute
  '/resources/outreach-templates': typeof ResourcesOutreachTemplatesRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/find-clients/': typeof FindClientsIndexRoute
  '/freelancers/': typeof FreelancersIndexRoute
  '/app/settings/danger-zone': typeof AppSettingsDangerZoneRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/subscription': typeof AppSettingsSubscriptionRoute
  '/find-clients/$skill/$city': typeof FindClientsSkillCityRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/365'
    | '/404'
    | '/500'
    | '/about'
    | '/app'
    | '/changelog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/safety'
    | '/services'
    | '/sitemap.xml'
    | '/support-us'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/app/ai-generator'
    | '/app/dashboard'
    | '/app/discover'
    | '/app/pipeline'
    | '/app/safety'
    | '/app/settings'
    | '/app/templates'
    | '/app/upgrade'
    | '/b2b/$category'
    | '/blog/$slug'
    | '/find-clients/$category'
    | '/find-clients/copywriter'
    | '/find-clients/dubai'
    | '/find-clients/graphic-designer'
    | '/find-clients/lagos'
    | '/find-clients/london'
    | '/find-clients/united-states'
    | '/find-clients/web-developer'
    | '/freelancers/$slug'
    | '/resources/export-guide'
    | '/resources/google-my-business'
    | '/resources/outreach-templates'
    | '/app/'
    | '/blog/'
    | '/find-clients/'
    | '/freelancers/'
    | '/app/settings/danger-zone'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/subscription'
    | '/find-clients/$skill/$city'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/365'
    | '/404'
    | '/500'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/safety'
    | '/services'
    | '/sitemap.xml'
    | '/support-us'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/app/ai-generator'
    | '/app/dashboard'
    | '/app/discover'
    | '/app/pipeline'
    | '/app/safety'
    | '/app/templates'
    | '/app/upgrade'
    | '/b2b/$category'
    | '/blog/$slug'
    | '/find-clients/$category'
    | '/find-clients/copywriter'
    | '/find-clients/dubai'
    | '/find-clients/graphic-designer'
    | '/find-clients/lagos'
    | '/find-clients/london'
    | '/find-clients/united-states'
    | '/find-clients/web-developer'
    | '/freelancers/$slug'
    | '/resources/export-guide'
    | '/resources/google-my-business'
    | '/resources/outreach-templates'
    | '/app'
    | '/blog'
    | '/find-clients'
    | '/freelancers'
    | '/app/settings/danger-zone'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/subscription'
    | '/find-clients/$skill/$city'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/365'
    | '/404'
    | '/500'
    | '/about'
    | '/app'
    | '/changelog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/safety'
    | '/services'
    | '/sitemap.xml'
    | '/support-us'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/app/ai-generator'
    | '/app/dashboard'
    | '/app/discover'
    | '/app/pipeline'
    | '/app/safety'
    | '/app/settings'
    | '/app/templates'
    | '/app/upgrade'
    | '/b2b/$category'
    | '/blog/$slug'
    | '/find-clients/$category'
    | '/find-clients/copywriter'
    | '/find-clients/dubai'
    | '/find-clients/graphic-designer'
    | '/find-clients/lagos'
    | '/find-clients/london'
    | '/find-clients/united-states'
    | '/find-clients/web-developer'
    | '/freelancers/$slug'
    | '/resources/export-guide'
    | '/resources/google-my-business'
    | '/resources/outreach-templates'
    | '/app/'
    | '/blog/'
    | '/find-clients/'
    | '/freelancers/'
    | '/app/settings/danger-zone'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/subscription'
    | '/find-clients/$skill/$city'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R365Route: typeof R365Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportUsRoute: typeof SupportUsRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  B2bCategoryRoute: typeof B2bCategoryRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FindClientsCategoryRoute: typeof FindClientsCategoryRoute
  FindClientsCopywriterRoute: typeof FindClientsCopywriterRoute
  FindClientsDubaiRoute: typeof FindClientsDubaiRoute
  FindClientsGraphicDesignerRoute: typeof FindClientsGraphicDesignerRoute
  FindClientsLagosRoute: typeof FindClientsLagosRoute
  FindClientsLondonRoute: typeof FindClientsLondonRoute
  FindClientsUnitedStatesRoute: typeof FindClientsUnitedStatesRoute
  FindClientsWebDeveloperRoute: typeof FindClientsWebDeveloperRoute
  FreelancersSlugRoute: typeof FreelancersSlugRoute
  ResourcesExportGuideRoute: typeof ResourcesExportGuideRoute
  ResourcesGoogleMyBusinessRoute: typeof ResourcesGoogleMyBusinessRoute
  ResourcesOutreachTemplatesRoute: typeof ResourcesOutreachTemplatesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FindClientsIndexRoute: typeof FindClientsIndexRoute
  FreelancersIndexRoute: typeof FreelancersIndexRoute
  FindClientsSkillCityRoute: typeof FindClientsSkillCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-us': {
      id: '/support-us'
      path: '/support-us'
      fullPath: '/support-us'
      preLoaderRoute: typeof SupportUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/365': {
      id: '/365'
      path: '/365'
      fullPath: '/365'
      preLoaderRoute: typeof R365RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers/': {
      id: '/freelancers/'
      path: '/freelancers'
      fullPath: '/freelancers/'
      preLoaderRoute: typeof FreelancersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/': {
      id: '/find-clients/'
      path: '/find-clients'
      fullPath: '/find-clients/'
      preLoaderRoute: typeof FindClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/resources/outreach-templates': {
      id: '/resources/outreach-templates'
      path: '/resources/outreach-templates'
      fullPath: '/resources/outreach-templates'
      preLoaderRoute: typeof ResourcesOutreachTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/google-my-business': {
      id: '/resources/google-my-business'
      path: '/resources/google-my-business'
      fullPath: '/resources/google-my-business'
      preLoaderRoute: typeof ResourcesGoogleMyBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/export-guide': {
      id: '/resources/export-guide'
      path: '/resources/export-guide'
      fullPath: '/resources/export-guide'
      preLoaderRoute: typeof ResourcesExportGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers/$slug': {
      id: '/freelancers/$slug'
      path: '/freelancers/$slug'
      fullPath: '/freelancers/$slug'
      preLoaderRoute: typeof FreelancersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/web-developer': {
      id: '/find-clients/web-developer'
      path: '/find-clients/web-developer'
      fullPath: '/find-clients/web-developer'
      preLoaderRoute: typeof FindClientsWebDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/united-states': {
      id: '/find-clients/united-states'
      path: '/find-clients/united-states'
      fullPath: '/find-clients/united-states'
      preLoaderRoute: typeof FindClientsUnitedStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/london': {
      id: '/find-clients/london'
      path: '/find-clients/london'
      fullPath: '/find-clients/london'
      preLoaderRoute: typeof FindClientsLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/lagos': {
      id: '/find-clients/lagos'
      path: '/find-clients/lagos'
      fullPath: '/find-clients/lagos'
      preLoaderRoute: typeof FindClientsLagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/graphic-designer': {
      id: '/find-clients/graphic-designer'
      path: '/find-clients/graphic-designer'
      fullPath: '/find-clients/graphic-designer'
      preLoaderRoute: typeof FindClientsGraphicDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/dubai': {
      id: '/find-clients/dubai'
      path: '/find-clients/dubai'
      fullPath: '/find-clients/dubai'
      preLoaderRoute: typeof FindClientsDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/copywriter': {
      id: '/find-clients/copywriter'
      path: '/find-clients/copywriter'
      fullPath: '/find-clients/copywriter'
      preLoaderRoute: typeof FindClientsCopywriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clients/$category': {
      id: '/find-clients/$category'
      path: '/find-clients/$category'
      fullPath: '/find-clients/$category'
      preLoaderRoute: typeof FindClientsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/$category': {
      id: '/b2b/$category'
      path: '/b2b/$category'
      fullPath: '/b2b/$category'
      preLoaderRoute: typeof B2bCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety': {
      id: '/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-generator': {
      id: '/app/ai-generator'
      path: '/ai-generator'
      fullPath: '/app/ai-generator'
      preLoaderRoute: typeof AppAiGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/find-clients/$skill/$city': {
      id: '/find-clients/$skill/$city'
      path: '/find-clients/$skill/$city'
      fullPath: '/find-clients/$skill/$city'
      preLoaderRoute: typeof FindClientsSkillCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/subscription': {
      id: '/app/settings/subscription'
      path: '/subscription'
      fullPath: '/app/settings/subscription'
      preLoaderRoute: typeof AppSettingsSubscriptionRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/danger-zone': {
      id: '/app/settings/danger-zone'
      path: '/danger-zone'
      fullPath: '/app/settings/danger-zone'
      preLoaderRoute: typeof AppSettingsDangerZoneRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsDangerZoneRoute: typeof AppSettingsDangerZoneRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSubscriptionRoute: typeof AppSettingsSubscriptionRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsDangerZoneRoute: AppSettingsDangerZoneRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSubscriptionRoute: AppSettingsSubscriptionRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAiGeneratorRoute: typeof AppAiGeneratorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSafetyRoute: typeof AppSafetyRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiGeneratorRoute: AppAiGeneratorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSafetyRoute: AppSafetyRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTemplatesRoute: AppTemplatesRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R365Route: R365Route,
  R404Route: R404Route,
  R500Route: R500Route,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportUsRoute: SupportUsRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  B2bCategoryRoute: B2bCategoryRoute,
  BlogSlugRoute: BlogSlugRoute,
  FindClientsCategoryRoute: FindClientsCategoryRoute,
  FindClientsCopywriterRoute: FindClientsCopywriterRoute,
  FindClientsDubaiRoute: FindClientsDubaiRoute,
  FindClientsGraphicDesignerRoute: FindClientsGraphicDesignerRoute,
  FindClientsLagosRoute: FindClientsLagosRoute,
  FindClientsLondonRoute: FindClientsLondonRoute,
  FindClientsUnitedStatesRoute: FindClientsUnitedStatesRoute,
  FindClientsWebDeveloperRoute: FindClientsWebDeveloperRoute,
  FreelancersSlugRoute: FreelancersSlugRoute,
  ResourcesExportGuideRoute: ResourcesExportGuideRoute,
  ResourcesGoogleMyBusinessRoute: ResourcesGoogleMyBusinessRoute,
  ResourcesOutreachTemplatesRoute: ResourcesOutreachTemplatesRoute,
  BlogIndexRoute: BlogIndexRoute,
  FindClientsIndexRoute: FindClientsIndexRoute,
  FreelancersIndexRoute: FreelancersIndexRoute,
  FindClientsSkillCityRoute: FindClientsSkillCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
